### ISSUE TITLE
Does this work with Stock FW v1.5 (2022.01.08)?

### ISSUE THREAD

**Issue by esmith13** [nicosensei/miyoo-mini-better-sd-card#2]
Sorry for the "issue" but didn't know where to ask.

Does this work with the official/stock FW v1.5 that was released on Jan. 8th, 2022?

https://lemiyoo-cn.translate.goog/upgrade/352.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US

**Comment by nicosensei** [comment]
Hi,

I haven't yet tested it. I plan to do so asap.

I'll update the issue when I do so.

**Comment by CloneIX** [comment]
Any update for us on compatability? I am eagerly waiting to test your enhancements!
Thank you for this either way.

**Comment by nicosensei** [comment]
Hi again, please check the latest release (20220115). It's updated, among other things, for the 20210108 firmware.

**Comment by CloneIX** [comment]
Awesome! Just started the upgrade process.
